### ISSUE TITLE
update of t4gpd

### ISSUE THREAD

**Issue by s-martiz** [thomas-leduc/t4gpd#3]
Dear @thomas-leduc, 
First of all congrats for your work which is highly relevant from my point of view.
I have seen here (https://github.com/CZiang/3D-To-2.5D/blob/main/7_irrad_viz3d.py) that new functions of your projects have been developped such as t4gpd.energy.geoProcesses.
Have you planned to update this GitHub repository soon ?
Best regards
Simon

**Comment by thomas-leduc** [comment]
Dear @simonmarti1992,
Thank you for your interest and for this feedback. I plan to release a version 0.4.0 of the plugin by the end of July 2022.
Best regards,
Thomas
