### ISSUE TITLE
Estimation of view factors using ray casting (version 0.4.0+)

### ISSUE THREAD

**Issue by bbrangeo** [thomas-leduc/t4gpd#5]
Hi Thomas,

Example : Estimation of view factors using ray casting (version 0.4.0+) does not work. 

Bug in file MoveSensorsAwayFromSurface.py

n ==> return nan

`
    def runWithArgs(self, row):
        p = row.geometry
        assert isinstance(p, Point), 'sensorsGdf must be a GeoDataFrame of Points'
        n = row[self.normalFieldname]
        # print(p.x )
        # print(self.dist)
        # print(n)
        # print(type(n))
        # import math
        #
        # if isinstance(n,float) and math.isnan(n):
        #     n=(0,0,0)

        return { 'geometry': Point([
            p.x + self.dist * n[0],
            p.y + self.dist * n[1],
            p.z + self.dist * n[2],
            ]) }

`

Boris

**Comment by thomas-leduc** [comment]
Hi Boris,

Thank you for your vigilance and this quick feedback.

Indeed, the CirReader used to load the building model (via GeoDataFrameDemos5.cirSceneMasque1Corr()) doesn't embed any more information about the normal vectors of the faces. It is necessary to calculate them explicitly via the following instruction:
buildings['normal_vec'] = buildings.geometry.apply(lambda g: GeomLib3D.getFaceNormalVector(g))

I modify the documentation accordingly and invite you to reload the following page :
https://t4gpd-docs.readthedocs.io/en/latest/pyvista/#estimation-of-view-factors-using-ray-casting-version-040
